on: [push]
concurrency:
  group: production
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: l # can't rename it lol but this is the production environment
    steps:
      - uses: actions/checkout@v6
      - uses: meteor-actions/install@v6
      - run: npm install -g mup
      # Write environment variables that Meteor needs to a settings file
      - run: |
          echo "{
            \"BH_CLIENT_ID\": \"${{ secrets.BH_CLIENT_ID }}\",
            \"BH_CLIENT_SECRET\": \"${{ secrets.BH_CLIENT_SECRET }}\",
            \"public\": {
              \"COMMIT_SHA\": \"${{ github.sha }}\"
            }
          }" > .deploy/settings.json

      # Do the actual deploy
      - name: Deploy to server
        env:
          DEPLOY_SERVER_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          DEPLOY_SERVER_USERNAME: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          DEPLOY_SERVER_PASSWORD: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          DEPLOY_ROOT_URL: ${{ secrets.DEPLOY_ROOT_URL }}
          DEPLOY_MONGO_URL: ${{ secrets.DEPLOY_MONGO_URL }}
          DEPLOY_MONGO_OPLOG_URL: ${{ secrets.DEPLOY_MONGO_OPLOG_URL }}
          DEPLOY_PROXY_DOMAINS: ${{ secrets.DEPLOY_PROXY_DOMAINS }}
          DEPLOY_LETSENCRYPT_EMAIL: ${{ secrets.DEPLOY_LETSENCRYPT_EMAIL }}
        run: npm run deploy
